language: objective-c
osx_image: xcode7.3
xcode_workspace: WWDCScholars.xcodeproj
xcode_scheme: WWDCScholarsTests
script:
- "./fastlane/travis.sh"
cache:
- bundler
env:
  global:
  - secure: E6UaeB3qFv/M1iwFDWmh8GvPXFDfz7eCso+urZVdQPK8x2z5ZI6OKOhDaBvpAO2ks4eQTnYR/Yc1sfOlDlgZC5uBcdObCdh9JClZA+Hb0cktQWFCILm2t55Wa5t7RFEtI572TS+Wi2+21O23wlMiw9wU00Z2Ga9GztNUnlihZTzbXyNrJgv0QyFRzqaTjkPDwu0ezwi0DL1lfbOh+gn+IrATgsVrs0BnFUkItvzQ9/JeXBVZuwPqSFSlRVQeKJTH7ws9kf/M4+y9yZmJLev9gtjq/tLAKKkPdnm3y0LBsBiQyhj7KKKqxcJhxXVR3YQaV4vKj7xeG56Tlp7wxbcA3Qo6UlO63Zs/ovu2dFxTY0ODcsqRes+itz7fuQFKhC7hyd+6JujLT6ccpUiIgKIVaCLIoc5/asUqXmDvKDbZSiFHTOT402/vraZ332WJkL93HfTrE8epGVBgogkVL5u98iKTOTH/Q2fWo850sAHgejuo3AWQK3UoUIlorrDd0S9By44ijC5Z3LFGBpTRs45DbHSTAhkPQpQ/HYxo4JxwnUHAa7MlOUDZY9i8aMGRnav4ew8Vh3sxmGx1FNaHofx2XEKKa8Mx6Q4zGOBkTtKcF68uwUe25rKQT8RjC/FqLANsUstj+hJc+vZqVpMhg/AkOeOEj6+/IpfmgiXyKCGzxz4=
  - secure: ED6ZlTFSb1Z2N6CRvDDfvWB6DxjAuQWAxVudb6oC7wF00i9ja1hYAxkLUJTRPahs0Ab9L7ppI+4xt12k2Gc7btLLCNHkNBp3avnFL72GWE4FkL9nXnP/cppqtrU6YEIByeb2RHn8R00yBxEM39V5Etp+1ZFn1eggQotR2qTuCFOCmZrtLwLTV1AYlE5ufZL11c11k91hIuduFVRkTgleO6MRawJfd4+wVw8IyA8KReDXe1Q/qSEAMRZ4CU/V6VWIlxy06iC8Z/zCQvemGCFlYvddt/5/9zZoPTpyCFM8sHWGbVCBZuoZgdoqEmZBIbyIuwuMzDgfh1Uz2qkk0vh3Qas0YTJYxYU8pQXfjNBg7M9PmhmhcH0frZkn/W7aIC8irXWL4DpUEufNiNisDh5mel8+jliJ80dBX9IU5wDO+EF84QdDVro3cPVT2PjQSXRNMLwAehh1KR5jGglLmDVgXrmykI0Y8tWSJtDzNuR8D+OB/Bx6BIO4i8oC0M0FCZtnEk0Cq5Wkrv9xnh7A5soiYnE5qoHorHe56+le3pu9qp4vM8IHnbzg3+TyN7BrWMy/3Ok+c0P1ySAS6THVtQ2o9BfU2dX2Y6JoVgoxyjyh5WTzHLeSbmCgRs2GmWAm85NzuFSCxjB7+Vhi42yL1GjGVVoXzseNsv6WHgKaHKFW/EE=
  - secure: Wp0P2k3nkHY3iqUdt5NoZVuqMbTCt9y1yYISDnv17dLhoQnNn54h1vQjflg7zHwbitXuSJkXu8WGEMIJg3Qe5662mSzGv+nL7wCUa3FMihSORcnHdwA4sm6IK1vJgDQci/X5oEcUkSCmKO1zzFpM84mHm/PN9ajBAOlrd17fQAAi1XgG5ZIVCVj+x34UcHPw/rx2g36m3xvA92dpHOwR/7feKd2fV43HNiwQ+8GDoom1F3TL4fmPeKOjlfdO0qJJsmy+1ouGZzhFlTEE/jNqKzInVyKCUSORc//NmdpAD0ynBFu2tTV4Zct1FL4/eO6woU91H80Uxpz2E/FhopasXpElt6H6MlO6IAIsdW5Wh7hCDhjIQVtGaHlPLhQovO0rwoSXVh/Ouh7RuTKz2Dg7Z/cFppBvn/2ZHSwlYeODnDWjZP+NYJB0eAWZz3Ew4Df0J/M3WME7iCZzqPTk1cr2clH4bJpp14fsLX/lBWPpoRGDVnL1A6uaCfFQuSTxkxPyOXJ2KUZl3WAjceI6jTYhfzXLvE+Ge9SsKnbPdf/ObaBG7wTwae2MyqENBdlk/qstQ3HqF0woshlGFe7kI6g9F9Kw98NFC+z4h6MSlnPUowYs619jR85Pt8IRT1Ca6IAxsCc6rB5iOmDfv5672FsZyg4x2TyQ6BFB+fzoJPz5mN0=
email:
  recipients:
  - ci@logicbit.nl
  on_success: change
  on_failure: always
branches:
  only:
  - master
  - beta
  - release
before_install:
- openssl aes-256-cbc -K $encrypted_22d783a40343_key -iv $encrypted_22d783a40343_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- mv id_rsa ~/.ssh/id_rsa
